# This rule tells Netlify to proxy any request starting with /api
# to your backend server on Render.
[[redirects]]
  from = "/api/*"
  to = "https://college-glow-desk.onrender.com/api/:splat"
  status = 200